=== api-evangelist/amazon-iot-sitewise/json-schema/iot-sitewise-describe-time-series-response-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-iot-sitewise/refs/heads/main/json-schema/iot-sitewise-describe-time-series-response-schema.json",
  "title": "DescribeTimeSeriesResponse",
  "description": "DescribeTimeSeriesResponse schema",
  "type": "object",
  "properties": {
    "assetId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ID"
        },
        {
          "description": "The ID of the asset in which the asset property was created."
        }
      ]
    },
    "propertyId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ID"
        },
        {
          "description": "The ID of the asset property."
        }
      ]
    },
    "alias": {
      "allOf": [
        {
          "$ref": "#/components/schemas/PropertyAlias"
        },
        {
          "description": "The alias that identifies the time series."
        }
      ]
    },
    "timeSeriesId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TimeSeriesId"
        },
        {
          "description": "The ID of the time series."
        }
      ]
    },
    "dataType": {
      "allOf": [
        {
          "$ref": "#/components/schemas/PropertyDataType"
        },
        {
          "description": "<p>The data type of the time series.</p> <p>If you specify <code>STRUCT</code>, you must also specify <code>dataTypeSpec</code> to identify the type of the structure for this time series.</p>"
        }
      ]
    },
    "dataTypeSpec": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Name"
        },
        {
          "description": "<p>The data type of the structure for this time series. This parameter is required for time series that have the <code>STRUCT</code> data type.</p> <p>The options for this parameter depend on the type of the composite model in which you created the asset property that is associated with your time series. Use <code>AWS/ALARM_STATE</code> for alarm state in alarm composite models.</p>"
        }
      ]
    },
    "timeSeriesCreationDate": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Timestamp"
        },
        {
          "description": "The date that the time series was created, in Unix epoch time."
        }
      ]
    },
    "timeSeriesLastUpdateDate": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Timestamp"
        },
        {
          "description": "The date that the time series was last updated, in Unix epoch time."
        }
      ]
    },
    "timeSeriesArn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ARN"
        },
        {
          "description": "<p>The <a href=\"https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html\">ARN</a> of the time series, which has the following format.</p> <p> <code>arn:${Partition}:iotsitewise:${Region}:${Account}:time-series/${TimeSeriesId}</code> </p>"
        }
      ]
    }
  },
  "required": [
    "timeSeriesId",
    "dataType",
    "timeSeriesCreationDate",
    "timeSeriesLastUpdateDate",
    "timeSeriesArn"
  ]
}

=== api-evangelist/amazon-iot-sitewise/examples/iot-sitewise-describe-time-series-response-example.json
{
  "assetId": "id-abc123",
  "propertyId": "id-abc123",
  "alias": "example-value",
  "timeSeriesId": "id-abc123",
  "dataType": "example-value",
  "dataTypeSpec": "example-value",
  "timeSeriesCreationDate": "2025-03-15T14:30:00Z",
  "timeSeriesLastUpdateDate": "2025-03-15T14:30:00Z",
  "timeSeriesArn": "arn:aws:iot:us-east-1:123456789012:thing/example"
}
